all:
	@clear
	c++ *.cpp -Wall -Wextra -std=c++98 -o exersise
	./exersise 0
	@echo ============================================
	./exersise nan
	@echo ============================================
	./exersise 42
	@echo ============================================