all:
	clang++ *.cpp -Wall -Wextra -Werror -o megaphone
	@echo -------------------------------------------------------------------------
	./megaphone "shhhhh... I think the students are asleep..."
	@echo -------------------------------------------------------------------------
	./megaphone Damnit " ! " "Sorry students, I thought this thing was off."
	@echo -------------------------------------------------------------------------
	./megaphone
	@echo -------------------------------------------------------------------------